services:
- type: web
  name: telebot-mvp
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: 6918129180:AAE-VI14THjHS48zfZN-XRZfPAbszvae9e0
    sync: false
  - key: WEBHOOK_SECRET
    value: very_long_random_secret_string
