services:
  - type: web
    name: tg-closed-group-bot
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    envVars:
      # === Telegram ===
      - key: BOT_TOKEN
        sync: false                  # поставиш у Dashboard (Secrets)

      - key: WEBHOOK_SECRET
        value: super_long_random_secret_123

      # === Google Ads ===
      - key: GOOGLE_ADS_YAML
        sync: false
      - key: GA_CUSTOMER_ID
        sync: false                  # Напр. 1234567890 (БЕЗ дефісів)
      - key: GA_CONVERSION_ACTION_ID
        sync: false

      # === (Опційно) Google Sheets backend ===
      # - key: GSA_CREDENTIALS
      #   sync: false                 # Весь JSON Service Account (тільки якщо треба стале сховище)
      # - key: SHEET_ID
      #   sync: false
